#![doc = "Peripheral access API for CW32L010 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 2;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
unsafe extern "C" {
    fn WDT();
    fn LVD();
    fn RTC();
    fn FLASHRAM();
    fn SYSCTRL();
    fn GPIOA();
    fn GPIOB();
    fn ADC();
    fn ATIM();
    fn VC1();
    fn VC2();
    fn GTIM1();
    fn LPTIM();
    fn BTIM1();
    fn BTIM2();
    fn BTIM3();
    fn I2C1();
    fn SPI();
    fn UART1();
    fn UART2();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[unsafe(link_section = ".vector_table.interrupts")]
#[unsafe(no_mangle)]
pub static __INTERRUPTS: [Vector; 29] = [
    Vector { _handler: WDT },
    Vector { _handler: LVD },
    Vector { _handler: RTC },
    Vector { _handler: FLASHRAM },
    Vector { _handler: SYSCTRL },
    Vector { _handler: GPIOA },
    Vector { _handler: GPIOB },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: ADC },
    Vector { _handler: ATIM },
    Vector { _handler: VC1 },
    Vector { _handler: VC2 },
    Vector { _handler: GTIM1 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: LPTIM },
    Vector { _handler: BTIM1 },
    Vector { _handler: BTIM2 },
    Vector { _handler: BTIM3 },
    Vector { _handler: I2C1 },
    Vector { _reserved: 0 },
    Vector { _handler: SPI },
    Vector { _reserved: 0 },
    Vector { _handler: UART1 },
    Vector { _handler: UART2 },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - Watch Dog Timer Interrupt"]
    WDT = 0,
    #[doc = "1 - Low Voltage Detect Interrupt"]
    LVD = 1,
    #[doc = "2 - Real Time Clock Interrupt"]
    RTC = 2,
    #[doc = "3 - Flash/RAM Interrupt"]
    FLASHRAM = 3,
    #[doc = "4 - SYSCTRL Interupt"]
    SYSCTRL = 4,
    #[doc = "5 - GPIOA Interrupt"]
    GPIOA = 5,
    #[doc = "6 - GPIOB Interrupt"]
    GPIOB = 6,
    #[doc = "12 - ADC Interrupt"]
    ADC = 12,
    #[doc = "13 - Advanced Timer Interrupt"]
    ATIM = 13,
    #[doc = "14 - Voltage Comparator 1 Interrupt"]
    VC1 = 14,
    #[doc = "15 - Voltage Comparator 2 Interrupt"]
    VC2 = 15,
    #[doc = "16 - General Timer1 Interrupt"]
    GTIM1 = 16,
    #[doc = "19 - LPTIM Interrupt"]
    LPTIM = 19,
    #[doc = "20 - Base Timer1 Interrupt"]
    BTIM1 = 20,
    #[doc = "21 - Base Timer2 Interrupt"]
    BTIM2 = 21,
    #[doc = "22 - Base Timer3 Interrupt"]
    BTIM3 = 22,
    #[doc = "23 - I2C1 Interrupt"]
    I2C1 = 23,
    #[doc = "25 - SPI Interrupt"]
    SPI = 25,
    #[doc = "27 - UART1 Interrupt"]
    UART1 = 27,
    #[doc = "28 - UART2 Interrupt"]
    UART2 = 28,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "desc ADC"]
pub type Adc = crate::Periph<adc::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Adc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc").finish()
    }
}
#[doc = "desc ADC"]
pub mod adc;
#[doc = "desc ATIM"]
pub type Atim = crate::Periph<atim::RegisterBlock, 0x4000_1400>;
impl core::fmt::Debug for Atim {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Atim").finish()
    }
}
#[doc = "desc ATIM"]
pub mod atim;
#[doc = "Base Timer 1"]
pub type Btim1 = crate::Periph<btim1::RegisterBlock, 0x4000_4800>;
impl core::fmt::Debug for Btim1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Btim1").finish()
    }
}
#[doc = "Base Timer 1"]
pub mod btim1;
#[doc = "Base Timer 2"]
pub type Btim2 = crate::Periph<btim1::RegisterBlock, 0x4000_4840>;
impl core::fmt::Debug for Btim2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Btim2").finish()
    }
}
#[doc = "Base Timer 2"]
pub use self::btim1 as btim2;
#[doc = "Base Timer 3"]
pub type Btim3 = crate::Periph<btim1::RegisterBlock, 0x4000_4880>;
impl core::fmt::Debug for Btim3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Btim3").finish()
    }
}
#[doc = "Base Timer 3"]
pub use self::btim1 as btim3;
#[doc = "desc CRC"]
pub type Crc = crate::Periph<crc::RegisterBlock, 0x4002_3000>;
impl core::fmt::Debug for Crc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crc").finish()
    }
}
#[doc = "desc CRC"]
pub mod crc;
#[doc = "desc FLASH"]
pub type Flash = crate::Periph<flash::RegisterBlock, 0x4002_2000>;
impl core::fmt::Debug for Flash {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flash").finish()
    }
}
#[doc = "desc FLASH"]
pub mod flash;
#[doc = "desc GPIOA"]
pub type Gpioa = crate::Periph<gpioa::RegisterBlock, 0x4800_0000>;
impl core::fmt::Debug for Gpioa {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioa").finish()
    }
}
#[doc = "desc GPIOA"]
pub mod gpioa;
#[doc = "desc GPIOB"]
pub type Gpiob = crate::Periph<gpiob::RegisterBlock, 0x4800_0100>;
impl core::fmt::Debug for Gpiob {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiob").finish()
    }
}
#[doc = "desc GPIOB"]
pub mod gpiob;
#[doc = "General Timer 1"]
pub type Gtim1 = crate::Periph<gtim1::RegisterBlock, 0x4000_1800>;
impl core::fmt::Debug for Gtim1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gtim1").finish()
    }
}
#[doc = "General Timer 1"]
pub mod gtim1;
#[doc = "desc I2C1"]
pub type I2c1 = crate::Periph<i2c1::RegisterBlock, 0x4000_5800>;
impl core::fmt::Debug for I2c1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c1").finish()
    }
}
#[doc = "desc I2C1"]
pub mod i2c1;
#[doc = "desc IRMOD"]
pub type Irmod = crate::Periph<irmod::RegisterBlock, 0x4000_4080>;
impl core::fmt::Debug for Irmod {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irmod").finish()
    }
}
#[doc = "desc IRMOD"]
pub mod irmod;
#[doc = "desc IWDT"]
pub type Iwdt = crate::Periph<iwdt::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for Iwdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Iwdt").finish()
    }
}
#[doc = "desc IWDT"]
pub mod iwdt;
#[doc = "desc LPTIM"]
pub type Lptim = crate::Periph<lptim::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for Lptim {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lptim").finish()
    }
}
#[doc = "desc LPTIM"]
pub mod lptim;
#[doc = "desc RAM"]
pub type Ram = crate::Periph<ram::RegisterBlock, 0x4002_2400>;
impl core::fmt::Debug for Ram {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ram").finish()
    }
}
#[doc = "desc RAM"]
pub mod ram;
#[doc = "desc UART1"]
pub type Uart1 = crate::Periph<uart1::RegisterBlock, 0x4000_0c00>;
impl core::fmt::Debug for Uart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart1").finish()
    }
}
#[doc = "desc UART1"]
pub mod uart1;
#[doc = "desc UART2"]
pub type Uart2 = crate::Periph<uart1::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for Uart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart2").finish()
    }
}
#[doc = "desc UART2"]
pub use self::uart1 as uart2;
#[doc = "desc LVD"]
pub type Lvd = crate::Periph<lvd::RegisterBlock, 0x4000_00d0>;
impl core::fmt::Debug for Lvd {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lvd").finish()
    }
}
#[doc = "desc LVD"]
pub mod lvd;
#[doc = "desc RTC"]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x4000_4400>;
impl core::fmt::Debug for Rtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc").finish()
    }
}
#[doc = "desc RTC"]
pub mod rtc;
#[doc = "desc SPI"]
pub type Spi = crate::Periph<spi::RegisterBlock, 0x4000_0800>;
impl core::fmt::Debug for Spi {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi").finish()
    }
}
#[doc = "desc SPI"]
pub mod spi;
#[doc = "System Ctrl"]
pub type Sysctrl = crate::Periph<sysctrl::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Sysctrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sysctrl").finish()
    }
}
#[doc = "System Ctrl"]
pub mod sysctrl;
#[doc = "desc VC1"]
pub type Vc1 = crate::Periph<vc1::RegisterBlock, 0x4000_00a4>;
impl core::fmt::Debug for Vc1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Vc1").finish()
    }
}
#[doc = "desc VC1"]
pub mod vc1;
#[doc = "desc VC2"]
pub type Vc2 = crate::Periph<vc1::RegisterBlock, 0x4000_00b4>;
impl core::fmt::Debug for Vc2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Vc2").finish()
    }
}
#[doc = "desc VC2"]
pub use self::vc1 as vc2;
#[doc = "desc VCDIV"]
pub type Vcdiv = crate::Periph<vcdiv::RegisterBlock, 0x4000_00a0>;
impl core::fmt::Debug for Vcdiv {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Vcdiv").finish()
    }
}
#[doc = "desc VCDIV"]
pub mod vcdiv;
#[unsafe(no_mangle)]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "ADC"]
    pub adc: Adc,
    #[doc = "ATIM"]
    pub atim: Atim,
    #[doc = "BTIM1"]
    pub btim1: Btim1,
    #[doc = "BTIM2"]
    pub btim2: Btim2,
    #[doc = "BTIM3"]
    pub btim3: Btim3,
    #[doc = "CRC"]
    pub crc: Crc,
    #[doc = "FLASH"]
    pub flash: Flash,
    #[doc = "GPIOA"]
    pub gpioa: Gpioa,
    #[doc = "GPIOB"]
    pub gpiob: Gpiob,
    #[doc = "GTIM1"]
    pub gtim1: Gtim1,
    #[doc = "I2C1"]
    pub i2c1: I2c1,
    #[doc = "IRMOD"]
    pub irmod: Irmod,
    #[doc = "IWDT"]
    pub iwdt: Iwdt,
    #[doc = "LPTIM"]
    pub lptim: Lptim,
    #[doc = "RAM"]
    pub ram: Ram,
    #[doc = "UART1"]
    pub uart1: Uart1,
    #[doc = "UART2"]
    pub uart2: Uart2,
    #[doc = "LVD"]
    pub lvd: Lvd,
    #[doc = "RTC"]
    pub rtc: Rtc,
    #[doc = "SPI"]
    pub spi: Spi,
    #[doc = "SYSCTRL"]
    pub sysctrl: Sysctrl,
    #[doc = "VC1"]
    pub vc1: Vc1,
    #[doc = "VC2"]
    pub vc2: Vc2,
    #[doc = "VCDIV"]
    pub vcdiv: Vcdiv,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        unsafe { DEVICE_PERIPHERALS = true }
        Peripherals {
            adc: unsafe { Adc::steal() },
            atim: unsafe { Atim::steal() },
            btim1: unsafe { Btim1::steal() },
            btim2: unsafe { Btim2::steal() },
            btim3: unsafe { Btim3::steal() },
            crc: unsafe { Crc::steal() },
            flash: unsafe { Flash::steal() },
            gpioa: unsafe { Gpioa::steal() },
            gpiob: unsafe { Gpiob::steal() },
            gtim1: unsafe { Gtim1::steal() },
            i2c1: unsafe { I2c1::steal() },
            irmod: unsafe { Irmod::steal() },
            iwdt: unsafe { Iwdt::steal() },
            lptim: unsafe { Lptim::steal() },
            ram: unsafe { Ram::steal() },
            uart1: unsafe { Uart1::steal() },
            uart2: unsafe { Uart2::steal() },
            lvd: unsafe { Lvd::steal() },
            rtc: unsafe { Rtc::steal() },
            spi: unsafe { Spi::steal() },
            sysctrl: unsafe { Sysctrl::steal() },
            vc1: unsafe { Vc1::steal() },
            vc2: unsafe { Vc2::steal() },
            vcdiv: unsafe { Vcdiv::steal() },
        }
    }
}
